// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Repo;

namespace UserService.Repo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200520141955_PostcodeCoordinates")]
    partial class PostcodeCoordinates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelpMyStreet.PostcodeCoordinates.EF.Entities.PostcodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Postcode")
                        .IsUnique()
                        .HasName("UX_Postcode_Postcode");

                    b.HasIndex("Postcode", "IsActive")
                        .HasName("IX_Postcode_Postcode_IsActive")
                        .HasAnnotation("SqlServer:Include", new[] { "Latitude", "Longitude" });

                    b.HasIndex("Latitude", "Longitude", "IsActive")
                        .HasName("IX_Postcode_Latitude_Longitude_IsActive")
                        .HasAnnotation("SqlServer:Include", new[] { "Postcode" });

                    b.ToTable("Postcode","Address");
                });

            modelBuilder.Entity("HelpMyStreet.PostcodeCoordinates.EF.Entities.PostcodeEntityOldEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Postcode")
                        .IsUnique()
                        .HasName("UX_Postcode_Postcode");

                    b.HasIndex("Postcode", "IsActive")
                        .HasName("IX_Postcode_Postcode_IsActive")
                        .HasAnnotation("SqlServer:Include", new[] { "Latitude", "Longitude" });

                    b.HasIndex("Latitude", "Longitude", "IsActive")
                        .HasName("IX_Postcode_Latitude_Longitude_IsActive")
                        .HasAnnotation("SqlServer:Include", new[] { "Postcode" });

                    b.ToTable("Postcode_Old","Staging");
                });

            modelBuilder.Entity("HelpMyStreet.PostcodeCoordinates.EF.Entities.PostcodeEntitySwitchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Postcode")
                        .IsUnique()
                        .HasName("UX_Postcode_Postcode");

                    b.HasIndex("Postcode", "IsActive")
                        .HasName("IX_Postcode_Postcode_IsActive")
                        .HasAnnotation("SqlServer:Include", new[] { "Latitude", "Longitude" });

                    b.HasIndex("Latitude", "Longitude", "IsActive")
                        .HasName("IX_Postcode_Latitude_Longitude_IsActive")
                        .HasAnnotation("SqlServer:Include", new[] { "Postcode" });

                    b.ToTable("Postcode_Switch","Staging");
                });

            modelBuilder.Entity("HelpMyStreet.PostcodeCoordinates.EF.Entities.PostcodeStagingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Postcode_Staging","Staging");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.ChampionPostcode", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("UserId", "PostalCode");

                    b.HasIndex("UserId", "PostalCode")
                        .HasName("ix_PostalCode");

                    b.ToTable("ChampionPostcode","User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.PersonalDetails", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("OtherPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("UnderlyingMedicalCondition");

                    b.HasKey("UserId");

                    b.ToTable("PersonalDetails","UserPersonal");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.RegistrationHistory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<byte>("RegistrationStep");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime");

                    b.HasKey("UserId", "RegistrationStep");

                    b.ToTable("RegistrationHistory","User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.SupportActivity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<byte>("ActivityId")
                        .HasColumnName("ActivityID");

                    b.HasKey("UserId", "ActivityId");

                    b.ToTable("SupportActivity","User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.SupportPostcode", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("UserId", "PostalCode");

                    b.HasIndex("UserId", "PostalCode")
                        .HasName("ix_PostalCode");

                    b.ToTable("SupportPostcode","User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<bool?>("EmailSharingConsent");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnName("FirebaseUID")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool?>("HmscontactConsent")
                        .HasColumnName("HMSContactConsent");

                    b.Property<bool?>("IsVerified");

                    b.Property<bool?>("IsVolunteer");

                    b.Property<bool?>("MobileSharingConsent");

                    b.Property<bool?>("OtherPhoneSharingConsent");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool?>("StreetChampionRoleUnderstood");

                    b.Property<double?>("SupportRadiusMiles");

                    b.Property<bool?>("SupportVolunteersByPhone");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .HasName("ix_FirebaseUID");

                    b.ToTable("User","User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.ChampionPostcode", b =>
                {
                    b.HasOne("UserService.Repo.EntityFramework.Entities.User", "User")
                        .WithMany("ChampionPostcode")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ChampionPostcode_User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.PersonalDetails", b =>
                {
                    b.HasOne("UserService.Repo.EntityFramework.Entities.User", "User")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("UserService.Repo.EntityFramework.Entities.PersonalDetails", "UserId")
                        .HasConstraintName("FK_PersonalDetails_User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.RegistrationHistory", b =>
                {
                    b.HasOne("UserService.Repo.EntityFramework.Entities.User", "User")
                        .WithMany("RegistrationHistory")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RegistrationHistory_User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.SupportActivity", b =>
                {
                    b.HasOne("UserService.Repo.EntityFramework.Entities.User", "User")
                        .WithMany("SupportActivity")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_SupportActivity_User");
                });

            modelBuilder.Entity("UserService.Repo.EntityFramework.Entities.SupportPostcode", b =>
                {
                    b.HasOne("UserService.Repo.EntityFramework.Entities.User", "User")
                        .WithMany("SupportPostcode")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_SupportPostcode_User");
                });
#pragma warning restore 612, 618
        }
    }
}
